### PR TITLE
Minor typo in example

### PR DESCRIPTION
**Pull request by davidwallis**
fixed a minor typo in the example.

### CODE REVIEW

**Comment by davidwallis** [comment]
Added pester example too

**Comment by RamblingCookieMonster** [comment]
Nice Pester example!  Are there supposed to be two?  Any chance we could trim it down to one?

And thanks for catching the typo!

**Comment by davidwallis** [comment]
yeah we could change it to one, maybe the second as it splits describe blocks so follows similar to format-pester, I'll do a new pr. Monday 




On Sat, Jun 17, 2017 at 7:27 PM +0100, "Warren Frame" <notifications@github.com> wrote:












Nice Pester example!  Are there supposed to be two?  Any chance we could trim it down to one?


And thanks for catching the typo!

**Comment by davidwallis** [comment]
Trimmed as requested

**Comment by RamblingCookieMonster** [comment]
Awesome, thanks for putting in the time to write this up!

**Pull request merged**
